
### gsl2.2 installation directory
##/Users/subhajit/SOFTWARES/gsl-2.2.1/GSL_install

all: hyper_2by2
hyper_2by2: hyper_2by2.c	
	gcc -g -I/usr/local/include -Wall -o hyper_2by2 hyper_2by2.c -L/usr/local/lib -lgsl -lgslcblas -lm  
